export const GET_FRIENDS_START_ACTION = 'FRIENDS::GET_FRIENDS_START_ACTION';
export const GET_FRIENDS_SUCCESS_ACTION = 'FRIENDS::GET_FRIENDS_SUCCESS_ACTION';
export const GET_FRIENDS_ERROR_ACTION = 'FRIENDS::GET_FRIENDS_ERROR_ACTION';
